# Generated by Django 4.2.16 on 2026-05-24 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("households", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KitchenManager",
            fields=[
                ("manager_id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                (
                    "household",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="households.household",
                    ),
                ),
                (
                    "login",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.login"
                    ),
                ),
            ],
            options={
                "db_table": "managers_kitchen_manager",
            },
        ),
    ]
