# Generated by Django 4.2.16 on 2026-05-24 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("feedback_id", models.AutoField(primary_key=True, serialize=False)),
                ("feedback_text", models.TextField()),
                ("emoji_rating", models.CharField(blank=True, max_length=20)),
                ("feedback_date", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.login"
                    ),
                ),
            ],
            options={
                "db_table": "feedback_feedback",
                "ordering": ["-feedback_date", "-feedback_id"],
            },
        ),
    ]
