# Generated by Django 4.2.16 on 2026-05-24 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngredientReference",
            fields=[
                ("ref_id", models.AutoField(primary_key=True, serialize=False)),
                ("ingredient_name", models.CharField(max_length=100)),
                ("default_shelf_life_days", models.IntegerField(default=7)),
                (
                    "storage_type",
                    models.CharField(
                        choices=[
                            ("fridge", "Fridge"),
                            ("freezer", "Freezer"),
                            ("pantry", "Pantry"),
                            ("counter", "Counter"),
                        ],
                        default="pantry",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.category",
                    ),
                ),
            ],
            options={
                "db_table": "admin_panel_ingredient_reference",
                "ordering": ["ingredient_name"],
            },
        ),
    ]
