# Generated by Django 4.2.16 on 2026-05-24 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("households", "0001_initial"),
        ("inventory", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WasteLog",
            fields=[
                ("waste_id", models.AutoField(primary_key=True, serialize=False)),
                ("item_name", models.CharField(max_length=100)),
                ("quantity", models.FloatField()),
                ("unit", models.CharField(default="kg", max_length=20)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("expired", "Expired"),
                            ("overcooked", "Overcooked"),
                            ("spoiled", "Spoiled"),
                            ("over_purchased", "Over-purchased"),
                            ("other", "Other"),
                        ],
                        default="expired",
                        max_length=30,
                    ),
                ),
                ("estimated_cost", models.FloatField(default=0)),
                ("co2_equivalent", models.FloatField(default=0)),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.category",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="households.household",
                    ),
                ),
                (
                    "logged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.login",
                    ),
                ),
            ],
            options={
                "db_table": "waste_waste_log",
                "ordering": ["-logged_at"],
            },
        ),
    ]
