# Generated by Django 4.2.16 on 2026-05-24 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("households", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("icon", models.CharField(default="bi-egg-fried", max_length=50)),
                ("color_code", models.CharField(default="#52B788", max_length=7)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "db_table": "inventory_category",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PantryItem",
            fields=[
                ("item_id", models.AutoField(primary_key=True, serialize=False)),
                ("item_name", models.CharField(max_length=100)),
                ("quantity", models.FloatField(default=1)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "kg"),
                            ("g", "g"),
                            ("L", "L"),
                            ("ml", "ml"),
                            ("pcs", "pcs"),
                            ("packets", "packets"),
                            ("other", "other"),
                        ],
                        default="pcs",
                        max_length=20,
                    ),
                ),
                ("purchase_date", models.DateField()),
                ("expiry_date", models.DateField()),
                (
                    "storage_location",
                    models.CharField(
                        choices=[
                            ("fridge", "Fridge"),
                            ("freezer", "Freezer"),
                            ("pantry", "Pantry"),
                            ("counter", "Counter"),
                        ],
                        default="pantry",
                        max_length=20,
                    ),
                ),
                ("barcode", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("threshold", models.FloatField(default=0.5)),
                ("is_consumed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.login",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.category",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="households.household",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_pantry_item",
                "ordering": ["expiry_date"],
            },
        ),
    ]
