# Generated by Django 4.2.16 on 2026-05-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Household",
            fields=[
                ("household_id", models.AutoField(primary_key=True, serialize=False)),
                ("household_name", models.CharField(max_length=100)),
                (
                    "household_type",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("restaurant", "Restaurant"),
                            ("hotel", "Hotel"),
                            ("canteen", "Canteen"),
                            ("school", "School"),
                        ],
                        default="home",
                        max_length=20,
                    ),
                ),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=50)),
                ("pin_code", models.CharField(max_length=10)),
                ("join_code", models.CharField(max_length=6, unique=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_suspended", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "households_household",
                "ordering": ["-created_at"],
            },
        ),
    ]
