# Generated by Django 4.2.16 on 2026-05-24 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("households", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("plan_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                (
                    "slug",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("pro", "Pro"),
                            ("premium", "Premium"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("tagline", models.CharField(blank=True, max_length=200)),
                (
                    "price_monthly",
                    models.IntegerField(default=0, help_text="Price in INR per month"),
                ),
                (
                    "price_yearly",
                    models.IntegerField(default=0, help_text="Price in INR per year"),
                ),
                (
                    "max_items",
                    models.IntegerField(default=50, help_text="-1 = unlimited"),
                ),
                (
                    "max_members",
                    models.IntegerField(default=1, help_text="-1 = unlimited"),
                ),
                ("ai_access", models.BooleanField(default=False)),
                ("advanced_analytics", models.BooleanField(default=False)),
                ("pdf_csv_export", models.BooleanField(default=False)),
                ("priority_support", models.BooleanField(default=False)),
                ("badge_color", models.CharField(default="accent", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "subscriptions_plan",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("sub_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("pending", "Pending"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("auto_renew", models.BooleanField(default=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "household",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="households.household",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="subscriptions.plan",
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions_subscription",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("payment_id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.IntegerField(help_text="Amount in INR")),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("billing_cycle", models.CharField(default="monthly", max_length=10)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("card", "Credit/Debit Card"),
                            ("upi", "UPI"),
                            ("netbanking", "Net Banking"),
                            ("wallet", "Wallet"),
                        ],
                        default="card",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("pending", "Pending"),
                            ("refunded", "Refunded"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("transaction_id", models.CharField(max_length=64, unique=True)),
                ("masked_account", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="subscriptions.plan",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions_payment",
                "ordering": ["-created_at"],
            },
        ),
    ]
