# Generated by Django 4.2.16 on 2026-05-24 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("households", "0001_initial"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingList",
            fields=[
                ("list_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="Shopping List", max_length=100)),
                ("is_auto_generated", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="households.household",
                    ),
                ),
            ],
            options={
                "db_table": "shopping_shopping_list",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShoppingItem",
            fields=[
                ("item_id", models.AutoField(primary_key=True, serialize=False)),
                ("item_name", models.CharField(max_length=100)),
                ("quantity", models.FloatField(default=1)),
                ("unit", models.CharField(default="pcs", max_length=20)),
                ("is_purchased", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.category",
                    ),
                ),
                (
                    "shopping_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shopping.shoppinglist",
                    ),
                ),
            ],
            options={
                "db_table": "shopping_shopping_item",
            },
        ),
    ]
